import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { LeftSidebar } from "./components/left-sidebar";
import { Navbar } from "./components/ui/Navbar/Navbar";
import "./globals.css";
import ClientWrapper from "./providers/clientWrapper";
import { Bounce, ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Megabite CRM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        key={""}
        className={`h-screen ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientWrapper>
          <Navbar />
          <main className='flex gap-1'>
            <LeftSidebar />
            <div className='w-full'>{children}</div>
          </main>
          <ToastContainer
            position='top-center'
            autoClose={4000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick={true}
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme='colored'
            transition={Bounce}
          />
        </ClientWrapper>
      </body>
    </html>
  );
}
